[PHP]
post_max_size = 100M
upload_max_filesize = 100M
variables_order = EGPCS
memory_limit = 256M

[opcache]
opcache.enable_cli=1
opcache.jit=1254
opcache.jit_buffer_size=100M
opcache.memory_consumption=256
opcache.max_accelerated_files=20000
opcache.validate_timestamps=0
